In [50]:


#to add data from batch_table_sheet to sql table;
import psycopg2
import csv
conn = psycopg2.connect("host='localhost' port='5432' dbname='sumiran' user='postgres' password='SUMIran'")
cur = conn.cursor()
with open('batch_sheet.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # Skip the header row.
    
    for row in reader: 
        try:
        
            row = row[1],row[0]
            cur.execute(
            "INSERT INTO batch_table VALUES (%s, %s)",
             
             row)
            
        
        except Exception as e :
            print(e)
            conn.rollback()
        
            pass

            
        
conn.commit()

In [25]:
#sheet will return subject_name 
#get subject id from subject table
#add subject id with other data into sql table

In [48]:
#code for updating teacher_table
import psycopg2
import csv
conn = psycopg2.connect("host='localhost' port='5432' dbname='sumiran' user='postgres' password='SUMIran'")
cur = conn.cursor()
data = dict()  
with open('teacher_data1a.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # Skip the header row.
    for row in reader:
        #saving batch table as dict
           
                cur.execute("select * from subject_table")
                datum = cur.fetchall()
                
#print(datum)               

for i in range (0 ,len(datum)):
    data[datum[i][1]]= datum[i][0]
print(data)

with open('teacher_data1a.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # Skip the header row.    
    
    
    for row in reader: 
        #adding data to sql 
        print(data["physics"])
        try:
            print(row[2])
            print('avm')
            print(data[row[2]])
            
            rown = row[0], row[1], data[row[2]]
            print("value",rown)
            
            cur.execute(
            "INSERT INTO teacher_data1 VALUES (%s, %s, %s)",
             rown
             )
            
            
        
        except Exception as e :
            #print(e)
            conn.rollback()
        
            pass
    
    
    
conn.commit()

{'physics': '1', 'chemistry': '2', 'maths': '3', 'english': '4', 'hindi': '5', 'arts': '6'}
1
physics
avm
1
value ('19', 'Dov Houndson', '1')
1
chemistry
avm
2
value ('20', 'Carmine Farlane', '2')
1
maths
avm
3
value ('21', 'Albrecht McGregor', '3')
1
english
avm
4
value ('22', 'Elinore Lille', '4')
1
hindi
avm
5
value ('23', 'Robbie Wrathall', '5')
1
arts
avm
6
value ('24', 'Prinz Srawley', '6')
1
physics
avm
1
value ('25', 'Gillian Fearick', '1')
1
chemistry
avm
2
value ('7', 'Rodolfo De Giovanni', '2')
1
maths
avm
3
value ('9', 'Gannon Elph', '3')
1
english
avm
4
value ('10', 'Genevieve Flaherty', '4')
1
hindi
avm
5
value ('11', 'Wendeline Dikle', '5')
1
arts
avm
6
value ('12', 'Erina Towers', '6')
1
physics
avm
1
value ('13', 'Ronica Shuttle', '1')
1
chemistry
avm
2
value ('14', 'Ardeen Aspin', '2')
1
maths
avm
3
value ('15', 'Rudolph Buttle', '3')
1
english
avm
4
value ('16', 'Dania Fittes', '4')
1
hindi
avm
5
value ('17', 'Guinna Wornum', '5')
1
arts
avm
6
value ('18', 'Sayre Vonderdell', '6')

In [46]:
#to add data from subject_sheet to sql table;
import psycopg2
import csv
conn = psycopg2.connect("host='localhost' port='5432' dbname='sumiran' user='postgres' password='SUMIran'")
cur = conn.cursor()
with open('subject_sheet.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # Skip the header row.
    
    for row in reader: 
        try:
        
            cur.execute(
            "INSERT INTO subject_table VALUES (%s, %s)",
             row
             )
            
        
        except Exception as e :
            print(e)
            conn.rollback()
        
            pass

            
        
conn.commit()

#trash data

print(type(datum))
data = dict()  
for row in reader:
       cur.execute("select batch_name from student_data1")
        
data.add(cur.fetchall())
print(data)
               
        for row in reader:
           
                cur.execute("select batch_name from student_data1")
                datum = cur.fetchall()
                print(datum)
                data.add(datum)
                cur.execute("select batch_name from student_data1")        
                datam2 = cur.fetchall()
            #fetching the key value and adding it to sql
            
            #cur.execute(
            #"INSERT INTO student_data1 VALUES (%s)",
             #data[row[4]]
             #)
         import psycopg2
import csv
conn = psycopg2.connect("host='localhost' port='5432' dbname='postgres' user='postgres' password='SUMIran'")
cur = conn.cursor()
data = dict()  
with open('student_datasheet.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # Skip the header row.
    
    for row in reader: 
        cur.execute(
            "INSERT INTO student_data1 VALUES (%s, %s, %s, %s)",
             row
             )
        cur.execute(
            "INSERT INTO student_data1 VALUES (%s)",
             data[row[4]]
             )
#to get batch_name from excel 
#check value to batch_name in data 
#enter value to sql table